ALTER TABLE Cosplans
ADD FOREIGN KEY (Franchise_Nr)
REFERENCES Franchises (Nummer)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Cosplans
ADD FOREIGN KEY (Bild_Nr)
REFERENCES Bilder (Nummer)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Bilder
ADD FOREIGN KEY (Cosplan_Nr)
REFERENCES Cosplans (Nummer)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ToDos
ADD FOREIGN KEY (Cosplan_Nr)
REFERENCES Cosplans (Nummer)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE ToDos
ADD FOREIGN KEY (Kategorie_Nr)
REFERENCES ToDoKategorien (Nummer)
ON DELETE CASCADE
ON UPDATE CASCADE;